version = "3.10.4"
runner.dialect = scala3
maxColumn = 140

align.preset = more

binPack.callSite = false
binPack.defnSite = false

continuationIndent.callSite = 2
continuationIndent.defnSite = 2

newlines.configStyle.callSite.prefer = true
newlines.configStyle.defnSite.prefer = true

danglingParentheses.callSite = true
danglingParentheses.defnSite = true

rewrite.rules = [RedundantParens, SortImports]
rewrite.insertBraces.minLines = 1
rewrite.insertBraces.allBlocks = true

rewrite.scala3.convertToNewSyntax = false
rewrite.scala3.removeOptionalBraces.enabled = false

optIn.breakChainOnFirstMethodDot = true
